version: '3.8'

networks:
  myNetwork:

services:
  postgres:
    image: postgres:15
    container_name: quarkus_postgres
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: logsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus/quarkus-logs-manager-jvm
    container_name: quarkus-logs-manager
    depends_on:
      - postgres
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://postgres:5432/logsdb
      - QUARKUS_DATASOURCE_USERNAME=quarkus
      - QUARKUS_DATASOURCE_PASSWORD=quarkus
      - SECURITY_DEFAULT_ADMIN_PASSWORD=logAdmin
      - SECURITY_DEFAULT_USER_PASSWORD=logUser
    ports:
      - "8080:8080"

volumes:
  postgres_data: